# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9d7e0ae5ee4d974620ac4344969c97bfa866c1e4dde109805855758fc17dbabc3683ca581b59e2590dcd90e575107ae6b8cb80cfdb953b50660e0bbd1a8ceb2

test:
  secret_key_base: 795048af26abb247be7e7b460885b0102733eb51cc24e3a7f97583b6d82f6a104735969dd48c13e62b0ff86af121283ebc7450dc3a4da88bddc68881fe2a5ce6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
